version: '3.9'

services:
  api:
    build:
      context: ./backend 
    container_name: booking-api
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/travelbooking
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    restart: unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: booking-frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://api:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped

  mongo:
    image: mongo:6
    command: mongod --quiet --logpath=/dev/null
    container_name: travel-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: